#!/usr/bin/env bash
# Interactive storage setup for this ARM fork.
# - Optional NAS mount under /mnt (NFS, CIFS/SMB, or existing path)
# - Writes docker-compose.nas.yml so media/music land on the NAS
# - Prints SFTP tips for pulling completed rips
set -euo pipefail

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_COMPOSE="${ROOT}/docker-compose.nas.yml"
OUT_ENV="${ROOT}/.env.nas"
FSTAB_BACKUP=""

prompt() {
  local msg="$1"
  local default="${2:-}"
  local reply
  if [[ -n "${default}" ]]; then
    read -r -p "${msg} [${default}]: " reply || true
    echo "${reply:-$default}"
  else
    read -r -p "${msg}: " reply || true
    echo "${reply}"
  fi
}

prompt_yn() {
  local msg="$1"
  local default="${2:-n}"
  local reply
  read -r -p "${msg} [y/N]: " reply || true
  reply="${reply:-$default}"
  [[ "${reply}" =~ ^[Yy]$ ]]
}

require_root_for_mount() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo -e "${YELLOW}Mount/fstab changes need root. Re-run with sudo for that part,${NC}"
    echo -e "${YELLOW}or choose 'existing' if the NAS is already mounted.${NC}"
    return 1
  fi
  return 0
}

write_nas_compose() {
  local media_host="$1"
  local music_host="$2"
  local include_nvidia="${3:-0}"

  mkdir -p "${media_host}" "${music_host}" 2>/dev/null || true

  cat >"${OUT_COMPOSE}" <<EOF
# Generated by scripts/installers/configure-storage.sh
# Media/music on NAS (or local /mnt paths). Keep config/logs/home on local disk.
#
# Start:
#   docker compose -f docker-compose.yml -f docker-compose.nas.yml up -d
# With NVIDIA:
#   docker compose -f docker-compose.yml -f docker-compose.nvidia.yml -f docker-compose.nas.yml up -d

services:
  arm:
    volumes:
      - ${media_host}:/home/arm/media
      - ${music_host}:/home/arm/music
EOF

  cat >"${OUT_ENV}" <<EOF
# Optional helpers for this NAS layout
ARM_NAS_MEDIA=${media_host}
ARM_NAS_MUSIC=${music_host}
EOF

  echo -e "${GREEN}Wrote ${OUT_COMPOSE}${NC}"
  echo -e "${GREEN}Wrote ${OUT_ENV}${NC}"
  if [[ "${include_nvidia}" == "1" ]]; then
    echo -e "Start with NVIDIA + NAS:"
    echo "  docker compose -f docker-compose.yml -f docker-compose.nvidia.yml -f docker-compose.nas.yml up -d"
  else
    echo -e "Start with NAS volumes:"
    echo "  docker compose -f docker-compose.yml -f docker-compose.nas.yml up -d"
  fi
}

setup_nfs() {
  local server share mount_point
  server="$(prompt "NFS server hostname or IP")"
  share="$(prompt "NFS export path" "/volume1/media")"
  mount_point="$(prompt "Local mount point" "/mnt/arm-media")"

  require_root_for_mount || return 1
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -y
    apt-get install -y nfs-common
  fi
  mkdir -p "${mount_point}"
  local fstab_line="${server}:${share}  ${mount_point}  nfs  defaults,_netdev,nofail  0  0"
  if ! grep -Fq "${server}:${share}" /etc/fstab 2>/dev/null; then
    cp -a /etc/fstab "/etc/fstab.bak.arm.$(date +%s)"
    echo "${fstab_line}" >>/etc/fstab
    echo -e "${GREEN}Added fstab entry for NFS.${NC}"
  fi
  mount "${mount_point}" || mount -a
  echo "${mount_point}"
}

setup_cifs() {
  local server share mount_point username credentials_file
  server="$(prompt "SMB/CIFS server hostname or IP")"
  share="$(prompt "Share name (e.g. media or //server/media)" "media")"
  # Accept //server/share or just share
  if [[ "${share}" != //* ]]; then
    share="//${server}/${share}"
  fi
  mount_point="$(prompt "Local mount point" "/mnt/arm-media")"
  username="$(prompt "SMB username" "arm")"
  credentials_file="/etc/arm-nas-credentials"

  require_root_for_mount || return 1
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -y
    apt-get install -y cifs-utils
  fi

  echo -e "${YELLOW}Enter SMB password (stored in ${credentials_file}, mode 600):${NC}"
  local password
  read -r -s -p "Password: " password || true
  echo
  umask 077
  cat >"${credentials_file}" <<EOF
username=${username}
password=${password}
EOF
  chmod 600 "${credentials_file}"
  mkdir -p "${mount_point}"

  local uid gid
  uid="$(id -u "${SUDO_USER:-root}" 2>/dev/null || echo 1000)"
  gid="$(id -g "${SUDO_USER:-root}" 2>/dev/null || echo 1000)"
  if id arm >/dev/null 2>&1; then
    uid="$(id -u arm)"
    gid="$(id -g arm)"
  fi

  local fstab_line="${share}  ${mount_point}  cifs  credentials=${credentials_file},uid=${uid},gid=${gid},iocharset=utf8,file_mode=0664,dir_mode=0775,_netdev,nofail  0  0"
  if ! grep -Fq "${share}" /etc/fstab 2>/dev/null; then
    cp -a /etc/fstab "/etc/fstab.bak.arm.$(date +%s)"
    echo "${fstab_line}" >>/etc/fstab
    echo -e "${GREEN}Added fstab entry for CIFS.${NC}"
  fi
  mount "${mount_point}" || mount -a
  echo "${mount_point}"
}

print_sftp_help() {
  local media_hint="${1:-./data/media}"
  cat <<EOF

${GREEN}=== Getting your rips via SFTP ===${NC}

Data in Docker usually lives on the host under the UID you set as ARM_UID
(often your login user or the 'arm' user), e.g.:

  ${media_hint}
  /home/arm/media          # if you use a host 'arm' user + bare paths
  ${ROOT}/data/media       # default compose layout

1) Prefer SSH keys (from your laptop):

  ssh-copy-id arm@YOUR_SERVER_IP
  sftp arm@YOUR_SERVER_IP

2) Or set a password for the arm user (on the server):

  sudo passwd arm
  sftp arm@YOUR_SERVER_IP

3) In the SFTP session:

  cd media/completed
  # or: cd $(basename "${media_hint}")/completed
  get -r .

4) If files are owned by your normal user instead of 'arm':

  sftp YOUR_USER@YOUR_SERVER_IP
  cd ${ROOT}/data/media/completed
  get -r .

5) Find where media actually is:

  docker inspect arm-rippers --format '{{range .Mounts}}{{println .Source "->" .Destination}}{{end}}'

EOF
}

main() {
  echo -e "${GREEN}ARM storage / NAS configurator${NC}"
  echo "Repo: ${ROOT}"
  echo

  print_sftp_help "${ROOT}/data/media"

  if ! prompt_yn "Map a NAS (or /mnt path) for ARM media/music volumes?"; then
    echo "Skipping NAS mapping. Default ./data/media and ./data/music remain."
    exit 0
  fi

  local kind media_mount music_mount
  kind="$(prompt "Mount type: nfs / cifs / existing" "existing")"
  case "${kind}" in
    nfs)
      media_mount="$(setup_nfs)"
      ;;
    cifs|smb)
      media_mount="$(setup_cifs)"
      ;;
    existing)
      media_mount="$(prompt "Existing media path on this host" "/mnt/arm-media")"
      if [[ ! -d "${media_mount}" ]]; then
        echo -e "${YELLOW}Creating ${media_mount}${NC}"
        mkdir -p "${media_mount}" || sudo mkdir -p "${media_mount}"
      fi
      ;;
    *)
      echo -e "${RED}Unknown type: ${kind}${NC}"
      exit 2
      ;;
  esac

  if prompt_yn "Use a separate path for music?"; then
    music_mount="$(prompt "Music path" "${media_mount%/}/music")"
    mkdir -p "${music_mount}" 2>/dev/null || sudo mkdir -p "${music_mount}"
  else
    music_mount="$(prompt "Music path (can be under media)" "${media_mount%/}/music")"
    mkdir -p "${music_mount}" 2>/dev/null || sudo mkdir -p "${music_mount}"
  fi

  # Ensure completed/raw trees exist for ARM
  mkdir -p "${media_mount}/completed" "${media_mount}/raw" "${media_mount}/transcode" 2>/dev/null \
    || sudo mkdir -p "${media_mount}/completed" "${media_mount}/raw" "${media_mount}/transcode"

  local nvidia=0
  if prompt_yn "Also include NVIDIA compose overlay when printing start command?"; then
    nvidia=1
  fi

  # Ownership hint
  if id arm >/dev/null 2>&1; then
    echo -e "${YELLOW}If permission errors appear, run:${NC}"
    echo "  sudo chown -R arm:arm '${media_mount}' '${music_mount}'"
  else
    echo -e "${YELLOW}If permission errors appear, run:${NC}"
    echo "  sudo chown -R \"\$(id -u):\$(id -g)\" '${media_mount}' '${music_mount}'"
  fi

  write_nas_compose "${media_mount}" "${music_mount}" "${nvidia}"
  print_sftp_help "${media_mount}"
}

main "$@"
